### ISSUE TITLE
StringIndexOutOfBoundsException: String index out of range: -1

### ISSUE THREAD

**Issue by ezebemmel** [cowmix88/Filebot-Scripts#1]
Hey,

I tried your script. I've got this error:

Processed 1 files
StringIndexOutOfBoundsException: String index out of range: -1
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
    at java_lang_String$substring$6.call(Unknown Source)
    at Script1$_run_closure72$_closure132.doCall(Script1.groovy:501)
    at Script1$_run_closure72.doCall(Script1.groovy:499)
    at Script1$_run_closure76.doCall(Script1.groovy:794)
    at Script1.run(Script1.groovy:566)
    at net.filebot.cli.ScriptShell.evaluate(ScriptShell.java:61)
    at net.filebot.cli.ScriptShell.runScript(ScriptShell.java:82)
    at net.filebot.cli.ArgumentProcessor.process(ArgumentProcessor.java:116)
    at net.filebot.Main.main(Main.java:169)

Can you fix it. Do you need more infos?

**Comment by cowmix88** [comment]
I think I pushed a fix, can you try it now?

**Comment by ezebemmel** [comment]
Yes. Thanks! It works.
