### ISSUE TITLE
[bug] [startup failed] With release of filebot 4.7 your script has stopped working.. :(

### ISSUE THREAD

**Issue by JourneyOver** [cowmix88/Filebot-Scripts#3]
As the title says, Rednoah released filebot 4.7 recently and it seems to have broken your script.. Would love to continue using your script as it's the only thing that is letting me use sonarr but I don't want to stay on outdated software either (I hate staying on outdated software) but I don't know enough about groovy to go in and fix this myself at all or I would :/ so would it be possible for you to either update the script or tell me what I need to change to get it working again. Would be greatly appreciated :)

Error below on what is happening now whenever the script executes.

> startup failed:
> Script1.groovy: 647: unable to resolve class net.filebot.web.CachedXmlResource 
>  @ line 647, column 13.
>                           dom = (new net.filebot.web.CachedXmlResource('https://raw.githubusercontent.com/ScudLee/anime-lists/master/anime-list.xml')).getDocument()
>                ^
> 
> Script1.groovy: 754: unable to resolve class net.filebot.web.CachedXmlResource 
>  @ line 754, column 12.
>                       dom = (new net.filebot.web.CachedXmlResource('https://raw.githubusercontent.com/ScudLee/anime-lists/master/anime-list.xml')).getDocument()
>               ^
> 
> 2 errors
> 
> org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
> Script1.groovy: 647: unable to resolve class net.filebot.web.CachedXmlResource 
>  @ line 647, column 13.
>                           dom = (new net.filebot.web.CachedXmlResource('https://raw.githubusercontent.com/ScudLee/anime-lists/master/anime-list.xml')).getDocument()
>                ^
> 
> Script1.groovy: 754: unable to resolve class net.filebot.web.CachedXmlResource 
>  @ line 754, column 12.
>                       dom = (new net.filebot.web.CachedXmlResource('https://raw.githubusercontent.com/ScudLee/anime-lists/master/anime-list.xml')).getDocument()
>               ^
> 
> 2 errors
> 
>   at net.filebot.cli.ScriptShell.evaluate(ScriptShell.java:62)
>   at net.filebot.cli.ScriptShell.runScript(ScriptShell.java:72)
>   at net.filebot.cli.ArgumentProcessor.runScript(ArgumentProcessor.java:114)
>   at net.filebot.cli.ArgumentProcessor.run(ArgumentProcessor.java:29)
>   at net.filebot.Main.main(Main.java:120)
> Failure (°_°)

**Comment by cowmix88** [comment]
Pushed a fix, sorry for the delay.

**Comment by JourneyOver** [comment]
Will test and let you know if its working as expected or not :) hope it is as I've been wanting to update filebot for a while now but been unable to.

**Comment by JourneyOver** [comment]
@cowmix88 it's still failing sadly on filebot 4.7.. :/ 

```
Parameter: ut_dir = C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET
Parameter: ut_kind = multi
Parameter: ut_title = Roots.2016.Part.2.720p.HDTV.x264-FLEET
Parameter: ut_label = 
 Parameter: seriesFormat = D:/Shows/TV Shows/{n}/season {s.pad(2)}/{n.replaceTrailingBrackets()} - {s00e00} - {t.replaceAll(/[!?.]+$/).replaceAll(/[\`´‘’?]/, /'/) .lowerTrail().replacePart(', Part $1')}
 Parameter: movieFormat = D:/Shows/Movies/{n} {[y]}/{n.replaceTrailingBrackets() replaceAll(/[!?.]+$/).replaceAll(/[\`´‘’?]/, /'/) lowerTrail()} [{y}]
 Parameter: animeFormat = D:/Shows/Anime/{n}/season {s.pad(2)}/{n.replaceTrailingBrackets()} - {s00e00} - {t.replaceAll(/[!?.]+$/).replaceAll(/[\`´‘’?]/, /'/) .lowerTrail().replacePart(', Part $1')}
 Parameter: deleteAfterExtract = y
 Parameter: clean = y
 Parameter: sonarr = *****
 Roots: [C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET]
 Read archive [roots.2016.part.2.720p.hdtv.x264-fleet.rar] and extract to [C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\.scratch\roots.2016.part.2.720p.hdtv.x264-fleet]
 Extracting files [C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\.scratch\roots.2016.part.2.720p.hdtv.x264-fleet\Roots.2016.Part.2.720p.HDTV.x264-FLEET.mkv]
 Index: 0, Size: 0
 java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at net.filebot.cli.ScriptShellBaseClass.getMediaInfo(ScriptShellBaseClass.java:449)
at Script1$_run_closure66$_closure116.doCall(Script1.groovy:357)
at Script1$_run_closure66$_closure116.doCall(Script1.groovy)
at net.filebot.cli.ScriptShellBaseClass.tryQuietly(ScriptShellBaseClass.java:119)
at Script1$_run_closure66.doCall(Script1.groovy:357)
at Script1.run(Script1.groovy:357)
at net.filebot.cli.ScriptShell.evaluate(ScriptShell.java:62)
at net.filebot.cli.ScriptShell.runScript(ScriptShell.java:72)
at net.filebot.cli.ArgumentProcessor.runScript(ArgumentProcessor.java:114)
at net.filebot.cli.ArgumentProcessor.run(ArgumentProcessor.java:29)
at net.filebot.Main.main(Main.java:120)
 Input: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\.scratch\roots.2016.part.2.720p.hdtv.x264-fleet\Roots.2016.Part.2.720p.HDTV.x264-FLEET.mkv
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.nfo
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r00
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r01
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r02
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r03
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r04
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r05
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r06
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r07
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r08
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r09
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r10
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r11
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r12
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r13
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r14
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r15
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r16
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r17
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r18
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r19
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r20
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r21
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r22
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r23
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r24
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r25
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r26
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r27
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r28
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r29
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r30
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r31
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r32
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r33
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r34
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r35
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r36
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r37
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r38
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r39
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r40
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r41
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r42
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r43
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r44
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r45
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r46
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r47
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r48
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r49
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r50
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r51
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r52
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r53
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r54
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r55
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r56
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r57
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r58
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r59
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.r60
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\roots.2016.part.2.720p.hdtv.x264-fleet.sfv
 Exclude: C:\Users\timta\Desktop\QBT\Roots.2016.Part.2.720p.HDTV.x264-FLEET\Sample\roots.2016.part.2.720p.hdtv.x264-fleet.sample.mkv
 Index: 0, Size: 0
 java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at net.filebot.cli.ScriptShellBaseClass.getMediaInfo(ScriptShellBaseClass.java:449)
at Script1$_run_closure38.doCall(Script1.groovy:95)
at Script1$_run_closure71.doCall(Script1.groovy:413)
at Script1.run(Script1.groovy:406)
at net.filebot.cli.ScriptShell.evaluate(ScriptShell.java:62)
at net.filebot.cli.ScriptShell.runScript(ScriptShell.java:72)
at net.filebot.cli.ArgumentProcessor.runScript(ArgumentProcessor.java:114)
at net.filebot.cli.ArgumentProcessor.run(ArgumentProcessor.java:29)
at net.filebot.Main.main(Main.java:120)
 Cannot invoke method tokenize() on null object
 java.lang.NullPointerException: Cannot invoke method tokenize() on null object
at Script1$_run_closure38.doCall(Script1.groovy:95)
at Script1$_run_closure71.doCall(Script1.groovy:413)
at Script1.run(Script1.groovy:406)
at net.filebot.cli.ScriptShell.evaluate(ScriptShell.java:62)
at net.filebot.cli.ScriptShell.runScript(ScriptShell.java:72)
at net.filebot.cli.ArgumentProcessor.runScript(ArgumentProcessor.java:114)
at net.filebot.cli.ArgumentProcessor.run(ArgumentProcessor.java:29)
at net.filebot.Main.main(Main.java:120)
 Failure (°_°)
```

is the newest log tested with a new show that come on yesterday.

**Comment by JourneyOver** [comment]
@cowmix88 this one is with a different episode/series

```
Parameter: ut_dir = C:\Users\timta\Desktop\QBT\11.22.63.S01E08.The.Day.In.Question.720p.HULU.WEBRip.AAC2.0.H.264-NTb.mkv
Parameter: ut_kind = multi
Parameter: ut_title = 11.22.63.S01E08.The.Day.In.Question.720p.HULU.WEBRip.AAC2.0.H.264-NTb.mkv
Parameter: ut_label = tv-sonarr
Parameter: seriesFormat = D:/Shows/TV Shows/{n}/season {s.pad(2)}/{n.replaceTrailingBrackets()} - {s00e00} - {t.replaceAll(/[!?.]+$/).replaceAll(/[\`´‘’?]/, /'/) .lowerTrail().replacePart(', Part $1')}
Parameter: movieFormat = D:/Shows/Movies/{n} {[y]}/{n.replaceTrailingBrackets() replaceAll(/[!?.]+$/).replaceAll(/[\`´‘’?]/, /'/) lowerTrail()} [{y}]
Parameter: animeFormat = D:/Shows/Anime/{n}/season {s.pad(2)}/{n.replaceTrailingBrackets()} - {s00e00} - {t.replaceAll(/[!?.]+$/).replaceAll(/[\`´‘’?]/, /'/) .lowerTrail().replacePart(', Part $1')}
Parameter: deleteAfterExtract = y
Parameter: clean = y
Parameter: sonarr = *****
Roots: [C:\Users\timta\Desktop\QBT\11.22.63.S01E08.The.Day.In.Question.720p.HULU.WEBRip.AAC2.0.H.264-NTb.mkv]
Index: 0, Size: 0
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at net.filebot.cli.ScriptShellBaseClass.getMediaInfo(ScriptShellBaseClass.java:449)
    at Script1$_run_closure66$_closure116.doCall(Script1.groovy:357)
    at Script1$_run_closure66$_closure116.doCall(Script1.groovy)
    at net.filebot.cli.ScriptShellBaseClass.tryQuietly(ScriptShellBaseClass.java:119)
    at Script1$_run_closure66.doCall(Script1.groovy:357)
    at Script1.run(Script1.groovy:357)
    at net.filebot.cli.ScriptShell.evaluate(ScriptShell.java:62)
    at net.filebot.cli.ScriptShell.runScript(ScriptShell.java:72)
    at net.filebot.cli.ArgumentProcessor.runScript(ArgumentProcessor.java:114)
    at net.filebot.cli.ArgumentProcessor.run(ArgumentProcessor.java:29)
    at net.filebot.Main.main(Main.java:120)
Input: C:\Users\timta\Desktop\QBT\11.22.63.S01E08.The.Day.In.Question.720p.HULU.WEBRip.AAC2.0.H.264-NTb.mkv
Index: 0, Size: 0
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at net.filebot.cli.ScriptShellBaseClass.getMediaInfo(ScriptShellBaseClass.java:449)
    at Script1$_run_closure38.doCall(Script1.groovy:95)
    at Script1$_run_closure71.doCall(Script1.groovy:413)
    at Script1.run(Script1.groovy:406)
    at net.filebot.cli.ScriptShell.evaluate(ScriptShell.java:62)
    at net.filebot.cli.ScriptShell.runScript(ScriptShell.java:72)
    at net.filebot.cli.ArgumentProcessor.runScript(ArgumentProcessor.java:114)
    at net.filebot.cli.ArgumentProcessor.run(ArgumentProcessor.java:29)
    at net.filebot.Main.main(Main.java:120)
Cannot invoke method tokenize() on null object
java.lang.NullPointerException: Cannot invoke method tokenize() on null object
    at Script1$_run_closure38.doCall(Script1.groovy:95)
    at Script1$_run_closure71.doCall(Script1.groovy:413)
    at Script1.run(Script1.groovy:406)
    at net.filebot.cli.ScriptShell.evaluate(ScriptShell.java:62)
    at net.filebot.cli.ScriptShell.runScript(ScriptShell.java:72)
    at net.filebot.cli.ArgumentProcessor.runScript(ArgumentProcessor.java:114)
    at net.filebot.cli.ArgumentProcessor.run(ArgumentProcessor.java:29)
    at net.filebot.Main.main(Main.java:120)
Failure (°_°)
```

this one seemed to pull out even more errors or something I don't even know...

**Comment by cowmix88** [comment]
Hmm I think that might be a bug with filebot itself, let me post on the forums

**Comment by JourneyOver** [comment]
@cowmix88  Dunno if you posted something new in here or not as I got a notification that I had a new response but I don't see one >.< but I did see you pushed some more stuff and I just tested it but it's still throwing the same errors as the last two posts I made. Only copying the error parts since they are exactly the same as above from the looks of it but this is running your newest push from today instead of yesterday.

```
Index: 0, Size: 0
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at net.filebot.cli.ScriptShellBaseClass.getMediaInfo(ScriptShellBaseClass.java:449)
    at Script1$_run_closure66$_closure116.doCall(Script1.groovy:357)
    at Script1$_run_closure66$_closure116.doCall(Script1.groovy)
    at net.filebot.cli.ScriptShellBaseClass.tryQuietly(ScriptShellBaseClass.java:119)
    at Script1$_run_closure66.doCall(Script1.groovy:357)
    at Script1.run(Script1.groovy:357)
    at net.filebot.cli.ScriptShell.evaluate(ScriptShell.java:62)
    at net.filebot.cli.ScriptShell.runScript(ScriptShell.java:72)
    at net.filebot.cli.ArgumentProcessor.runScript(ArgumentProcessor.java:114)
    at net.filebot.cli.ArgumentProcessor.run(ArgumentProcessor.java:29)
    at net.filebot.Main.main(Main.java:120)

Index: 0, Size: 0
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at net.filebot.cli.ScriptShellBaseClass.getMediaInfo(ScriptShellBaseClass.java:449)
    at Script1$_run_closure38.doCall(Script1.groovy:95)
    at Script1$_run_closure71.doCall(Script1.groovy:413)
    at Script1.run(Script1.groovy:406)
    at net.filebot.cli.ScriptShell.evaluate(ScriptShell.java:62)
    at net.filebot.cli.ScriptShell.runScript(ScriptShell.java:72)
    at net.filebot.cli.ArgumentProcessor.runScript(ArgumentProcessor.java:114)
    at net.filebot.cli.ArgumentProcessor.run(ArgumentProcessor.java:29)
    at net.filebot.Main.main(Main.java:120)
Cannot invoke method tokenize() on null object
java.lang.NullPointerException: Cannot invoke method tokenize() on null object
    at Script1$_run_closure38.doCall(Script1.groovy:95)
    at Script1$_run_closure71.doCall(Script1.groovy:413)
    at Script1.run(Script1.groovy:406)
    at net.filebot.cli.ScriptShell.evaluate(ScriptShell.java:62)
    at net.filebot.cli.ScriptShell.runScript(ScriptShell.java:72)
    at net.filebot.cli.ArgumentProcessor.runScript(ArgumentProcessor.java:114)
    at net.filebot.cli.ArgumentProcessor.run(ArgumentProcessor.java:29)
    at net.filebot.Main.main(Main.java:120)
```

**Comment by cowmix88** [comment]
Can you upload that video file somewhere? This might be a bug in filebot and not my script.

 Thanks!

**Comment by JourneyOver** [comment]
Yea I can in just a moment, testing newest push.

Thing is idk if its your script or filebot actually because this happened on two different series (since I only tested two at the time) and not on just one series.

Edit: test failed with same error again --- Uploading file now but its going to take a bit... :s will edit post again when upload is done with link to file.

Edit2: while I wait for this to upload still, I did forget to mention since you said it might be a bug with filebot I don't think it is actually because if I download the file and have filebot post process it like normal (without the use of your script but instead using the normal AMC script that comes with filebot)  it works as expected and it post processes the file like it should.

**Comment by cowmix88** [comment]
The places you're seeing errors seem to be pretty standard filebot calls so I'm not sure exactly what's going on, hopefully the error replicates on my machine once the file is uploaded.

**Comment by JourneyOver** [comment]
Well whatever the case may be hopefully we can get this figured out xD upload is at 20% as of typing. my upload speed is shit compared to download speed :c

Edit: 49% now still a ways to go :x

**Comment by JourneyOver** [comment]
@cowmix88 here you go - http://www.mediafire.com/download/jusy3c8wvd78hbt/11.22.63.S01E08.The.Day.In.Question.720p.HULU.WEBRip.AAC2.0.H.264-NTb.mkv

this was the latest show/series/episode I had downloaded to test out the newest pushes.

**Comment by cowmix88** [comment]
"File Blocked for Violation."

Wow that got denied quick lol

**Comment by JourneyOver** [comment]
Grrr thats annoying lol -.- idk where I could upload it that wouldn't get it taken down super quick like that..

**Comment by cowmix88** [comment]
I recommend Google drive and just delete it after I download it

**Comment by JourneyOver** [comment]
Alright will try google drive, funny that I uploaded it to both mega and mediafire and they both took it down super quick.

Edit: should take between 5-10 minutes to upload, so keep an eye out for the link so you can grab it quickly xD

**Comment by JourneyOver** [comment]
here hopefully you'll catch this one in time https://drive.google.com/open?id=0B2iDazQUc6pWcG4yTzlNbzJhS1E

**Comment by cowmix88** [comment]
Got it, will test shortly :)

**Comment by JourneyOver** [comment]
Okay :) hopefully you can figure things out and be able to fix whatever the issue is.

**Comment by cowmix88** [comment]
hmm it works fine on my machine, what OS are you using?

**Comment by JourneyOver** [comment]
running windows 10 x64 bit.

this is the command I'm running in qbittorrent --

> filebot -script C:\Users\timta\Dropbox\Public\Folders\Filebot\Groovy\amc.groovy --log-file amc.log --conflict override -non-strict --filter "age < 170" --def "ut_dir=%F" "ut_kind=multi" "ut_title=%N" "ut_label=%L" "seriesFormat=D:/Shows/TV Shows/{n}/season {s.pad(2)}/{n.replaceTrailingBrackets()} - {s00e00} - {t.replaceAll(/[!?.]+$/).replaceAll(/[`´‘’ʻ]/, /"'/") .lowerTrail().replacePart(', Part $1')}" "movieFormat=D:/Shows/Movies/{n} {[y]}/{n.replaceTrailingBrackets() replaceAll(/[!?.]+$/).replaceAll(/[`´‘’ʻ]/, /"'/") lowerTrail()} [{y}]" "animeFormat=D:/Shows/Anime/{n}/season {s.pad(2)}/{n.replaceTrailingBrackets()} - {s00e00} - {t.replaceAll(/[!?.]+$/).replaceAll(/[`´‘’ʻ]/, /"'/") .lowerTrail().replacePart(', Part $1')}" deleteAfterExtract=y clean=y "sonarr=localhost:8989/|6e7bff2e25e24317924907b16e6b7eee" 

Running it normal by changing the "C:\Users\timta\Dropbox\Public\Folders\Filebot\Groovy\amc.groovy" to fn:amc and deleting the sonarr stuff from my command makes everything run as normal but if I add the sonarr stuff back and change the fn:amc back to using "C:\Users\timta\Dropbox\Public\Folders\Filebot\Groovy\amc.groovy" it breaks and starts throwing up the error.

**Comment by cowmix88** [comment]
Hmm so it looks like the default amc script works for you. I've been looking into cleaning up and merging all the new amc changes into my version, maybe that will help. Thanks for being patient.

**Comment by JourneyOver** [comment]
yep default amc script works just fine for me, and haha I was actually going to suggest that at some point to maybe update your stuff with the new amc changes since your version of amc is like way outdated compared to a lot of the changes that have been put into the default amc script >.< hopefully it'll work for me if you clean up and merge the newest amc changes into your version but only time will tell. and its not a problem, I like your amc script so I'll be sticking around for as long as you update/support it as it is the only one that lets me use sonarr without having to worry about stuff.

**Comment by JourneyOver** [comment]
@cowmix88 how goes cleaning up and merging of the new amc changes? :o

**Comment by JourneyOver** [comment]
still working on merging stuff? :s haven't heard/seen anything new in a couple days now..

**Comment by cowmix88** [comment]
Sorry been swamped with work, I was about half way and I will try to finish soon :)

**Comment by JourneyOver** [comment]
Ah sorry haha, glad to know your still working on it though :D

**Comment by JourneyOver** [comment]
@cowmix88 hey man hows the updating/merging going? would love to get back to using this...

**Comment by JourneyOver** [comment]
@cowmix88 hey man I know it's been a long time, but any word on possibly fixing things up on this by chance?

**Comment by cowmix88** [comment]
Man I'm super sorry I had not been checking my github messages. I'm trying to figure out your issue but I'm a little stumped so far. Does it happen for you with all files or just certain files? I'm using filebot 4.7 but not seeing the same errors. I pushed some changes recently can you test them out?

**Comment by JourneyOver** [comment]
It's all good man, but I came up with something recently that'll update sonarr so you don't have to work on this error anymore if you don't want to (as the sonarr stuff was really the only thing I was wanting).. 

Rednoah ended up creating a groovy script for me to update sonarr pretty much exactly like your amc script does, so I can continue to use the latest amc script along with my groovy script..

```groovy
// TheTVDB ID
def id = id as int

// API Configuration
def url = new URL('http://localhost:8989')
def header = ['X-Api-Key': 'apikey']

def sonarrSeriesId = new JsonSlurper()
                         .parseText(new URL(url, '/api/series')
                                        .get(header)
                                        .text)
                         .find{ it.tvdbId == id }.id

println new URL(url, '/api/command').post(
   JsonOutput.toJson(
      [name: 'rescanSeries', seriesId: sonarrSeriesId]
   ).getBytes('UTF-8'),
   'application/json',
   header
).text
```

so I guess this can be closed now.
